#!/usr/bin/env node
/**
 * sync-figures.mjs — regenerate figures.json from user-manual/FIGURES.md.
 *
 * FIGURES.md is the documentation team's capture list: one table per chapter,
 * one row per figure, holding the key, where to capture it, which role to
 * capture it as, and the caption. That makes it the natural source of truth for
 * caption text, so figures.json is generated from it rather than maintained
 * alongside it.
 *
 *   node tools/sync-figures.mjs            # rewrite figures.json
 *   node tools/sync-figures.mjs --check    # exit 1 if figures.json is stale
 *
 * Only `caption` is carried across. Image paths are not stored: build.mjs
 * discovers `images/<key>.png` (or a numbered `images/NN-MM-<key>.png`) on its
 * own, so recapturing a screenshot under the right filename is all that is
 * needed to replace a placeholder.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const PRINT_DIR = resolve(HERE, '..');
const FIGURES_MD = resolve(PRINT_DIR, '..', 'user-manual', 'FIGURES.md');
const OUT = join(PRINT_DIR, 'figures.json');

/** Fixture-only figures: they illustrate the pipeline itself and are not screenshots. */
const FIXTURE_FIGURES = {
  'role-fencing-demo': {
    caption:
      'A chapter source file showing a role fence around an administrative section. The fenced block is present in the complete and org_admin editions and absent from the viewer edition.',
  },
  'tenant-branding-demo': {
    caption:
      'The same cover page rendered with ImpactMEL branding and with client branding, driven only by the theme arguments passed to the build.',
  },
  'figure-numbering-demo': {
    caption:
      'Figure labels are generated by CSS counters that reset at each chapter, so numbering stays correct whichever chapters an edition includes.',
  },
};

const stripInline = (s) =>
  s
    .replace(/`([^`]*)`/g, '$1')
    .replace(/\*\*([^*]*)\*\*/g, '$1')
    .replace(/\s+/g, ' ')
    .trim();

function parse(md) {
  const figures = {};
  const order = [];
  let chapter = null;

  for (const line of md.split('\n')) {
    const h = line.match(/^##\s+(?:(\d+)\s*[·.]\s*)?(.+?)\s*$/);
    if (h) {
      chapter = { number: h[1] ? Number(h[1]) : null, title: stripInline(h[2]) };
      continue;
    }
    if (!line.startsWith('|')) continue;

    const cells = line.split('|').slice(1, -1).map((c) => c.trim());
    if (cells.length < 2) continue;
    if (/^-{2,}$|^:?-+:?$/.test(cells[0])) continue; // separator row
    if (/^key$/i.test(cells[0])) continue; // header row

    const key = stripInline(cells[0]);
    if (!/^[a-z0-9][a-z0-9._-]*$/.test(key)) continue; // e.g. a `<key>` example

    const caption = stripInline(cells[cells.length - 1]);
    if (figures[key]) {
      console.warn(`  ! duplicate key "${key}" — keeping the first`);
      continue;
    }
    figures[key] = { caption, chapter: chapter?.title ?? null };
    order.push(key);
  }
  return { figures, order };
}

function build() {
  if (!existsSync(FIGURES_MD)) {
    throw new Error(`not found: ${FIGURES_MD}`);
  }
  const { figures, order } = parse(readFileSync(FIGURES_MD, 'utf8'));

  const out = {
    '//': [
      'GENERATED by tools/sync-figures.mjs from ../user-manual/FIGURES.md — do not',
      'hand-edit; edit FIGURES.md and re-run the tool. The fixture figures at the',
      'end are the exception: they live in the tool, not in FIGURES.md.',
      '',
      'Each {{figure:key}} placeholder in a chapter resolves to an entry here.',
      '  caption  the descriptive sentence printed after the generated "Figure N.M"',
      '  title    optional bold lead-in before the caption',
      '  src      optional explicit path; normally omitted, because build.mjs finds',
      '           images/<key>.png or images/NN-MM-<key>.png under imageRoots by',
      '           itself and falls back to a generated placeholder PNG when the',
      '           screenshot has not been captured yet',
    ],
    imageRoots: ['../public/user-manual', 'fixtures'],
    figures: {},
  };

  for (const key of order) out.figures[key] = { caption: figures[key].caption };
  for (const [key, v] of Object.entries(FIXTURE_FIGURES)) out.figures[key] = v;

  return { json: JSON.stringify(out, null, 2) + '\n', count: order.length };
}

const { json, count } = build();

if (process.argv.includes('--check')) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (current !== json) {
    console.error('figures.json is stale — run: node tools/sync-figures.mjs');
    process.exit(1);
  }
  console.log(`figures.json is up to date (${count} captured + ${Object.keys(FIXTURE_FIGURES).length} fixture figures)`);
} else {
  writeFileSync(OUT, json);
  console.log(
    `[sync-figures] ${count} figures from FIGURES.md + ${Object.keys(FIXTURE_FIGURES).length} fixture figures -> figures.json`
  );
}
